name: Github Actions Workshop
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
  weekday_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world when it's Monday"
        run: echo "Hello $FIRST_NAME $MIDDLE_NAME $LAST_NAME, today is Monday!"
        env:
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat

        # deploy: 
          # uses: JamesIves/github-pages-deploy-action@4.1.4
        # env:
        # lint:
          # run: npm run lint:ts
          # run: npm run lint:css
        # secret: secrets.PASSWORD
        # test: 
        #   run: npm test
        # timedDeploy:
        #     schedule: - cron:
        # docker1: docker/login-action
        # docker2: docker/metadata-action
        # docker3: docker/build-push-action
        # hacker: lirantal/is-website-vulnerable.github.io
        # conditional: 
        #   if: 
        # mail: dawidd6/action-send-mail
        # stats: anmol098/waka-readme-stats